### ISSUE TITLE
Unknown key "compiler"

### ISSUE THREAD

**Issue by lionseal** [wighawag/rocketh#1]
Hi Ronan! This key throws an error with solc 5.x, after removing it works fine.

https://github.com/wighawag/rocketh/blob/3b72bf4e491a922a28f0c327203922cc0bdcc4c3/lib.js#L146

**Comment by wighawag** [comment]
Thanks @lionseal it used to work with previous solc version, It was used to ensure the cache is reset if you use a different compiler. I ll just remove that for now but I ll add it in another way as for now changing compiler version will not break the cache.
